reposé pitase apuesta
caolin colará ericen
surgís ardías cuerdo
triste ebrias cambíe
acopla copero suecas
sentir retira trates
girado agrumo verdor
darías ansían cordón
rodado norias gringo
abasto cantor brusca
crudos iranio urdida
mastin sonora vitrina
gotera igneos ínterin
niegan barren adhiero
mojaba abjuro oraban
cociné léxica brillé
digito creido acetre
nutría tranca rechine
lidían dilema raería
opresa abombo recubre
