acede efe acodo
barre ríe bebés
abate etc abren
llame los luego
abres ore aisle
abecé efe abata
acudí ecu usado
buena use bucee
creas ser ceden
adore dar arcos
abecé ame abone
arnés aun arroz
deseo eso della
cifre cea clara
aisle vil volea
ancho aun anoto
coste ces corso
acaba eco adora
alego olé airee
acero ríe ancle
