aboco oses adulo
bramo obré comer
caoba aseo llore
impio orin icono
améis suma segué
abren orbe avive
bomba oiga sagas
alcen lama airee
abata obra oíste
asase aten postor
abeto bate tocan
basen raes labor
atroz grog agote
casco usas bambú
riáis irás diván
anime bien ebria
anude amen audaz
echas enea leerá
amolé almo mesas
ligar grúa llega
