asir cera acres surco
debe esbo deseo abril
arco croa colar frágil
arco creo cedro ardió
creo cese coser rocíen
toro acto traer beato
grúa cria raiga cocer
debe nada faene ocaso
asno ando ondas befes
brea obre oreja cacen
acné cual anulé abobé
eran ases ceras opaco
cria caer arcas señor
baje reja brame amemos
aten neto baten cuota
laxe pele lepra xxvii
ceas lisa liase reirá
ayer lame merla creer
grey ayer regia esotro
aire apio opere arcén
