legal lea jerga aliño
erais oro sarro impia
trabe ate batir abollo
laman cal calme esmeré
avale tel valen floto
banca una busca silbar
rotas oca actor tibio
seuda use pueda asáis
raido ida oiría sanees
aldea oso lados deseé
lides bis bisel asado
aires ase tersa guise
entra tan traen befase
reglé lea argel plegó
orlan loa sorna nidal
cosan neo sanea morís
cairo pio parco imito
casco use sueco gesta
optar sor prosa duplo
aldea ate edita flauta
