aboco aboco aboco obrase
abren abren abren elena
aboca aboca aboca faenen
brame brame brame arrimé
aptas aptas aptas pasito
abecé abecé abecé digné
actos actos actos postes
astil astil astil pulses
actor actor actor ocupe
ascos ascos ascos coerce
abren abren abren nombro
abril abril abril bienio
fluir fluir fluir arruga
aireé aireé aireé siglas
acres acres acres clases
abone abone abone peaje
rabia rabia rabia hierba
abecé abecé abecé chalo
aéreo aéreo aéreo deseé
bemol bemol bemol leíble
