anos anos anos anos anos unjo
abre abre abre abre abre rice
adán adán adán adán adán nenas
anis anis anis anis anis saben
alcé alcé alcé alcé alcé ellos
revi revi revi revi revi xxvi
ardo ardo ardo ardo ardo ondee
asan asan asan asan asan inste
abre abre abre abre abre labor
chau chau chau chau chau tutee
acné acné acné acné acné fiéis
abre abre abre abre abre cojee
baje baje baje baje baje llamé
alce alce alce alce alce colee
abro abro abro abro abro oible
ejes ejes ejes ejes ejes airee
ajos ajos ajos ajos ajos sovoz
ajos ajos ajos ajos ajos reloj
adán adán adán adán adán mitad
baúl baúl baúl baúl baúl llame
