abre abre abre iban
amen amen amen bombo
abre abre abre dador
abre abre abre roben
abre abre abre bife
abre abre abre lobo
abad abad abad calle
abre abre abre iban
abrí abrí abrí beato
acre acre acre eché
abro abro abro ébono
abre abre abre roban
alce alce alce bollo
alas alas alas señal
ante ante ante beato
abre abre abre hollé
abre abre abre robos
abre abre abre cacen
abre abre abre crome
abrí abrí abrí leal
