emana emana emana emana emana hornee
acero acero acero acero acero eider
borla borla borla borla borla grillo
abran abran abran abran abran calces
abecé abecé abecé abecé abecé llamé
abecé abecé abecé abecé abecé biselé
banco banco banco banco banco llamen
acebo acebo acebo acebo acebo retocó
aflui aflui aflui aflui aflui inunde
barca barca barca barca barca ciprio
andes andes andes andes andes llorón
alien alien alien alien alien ediles
aflui aflui aflui aflui aflui ufanía
ondea ondea ondea ondea ondea accedí
abrió abrió abrió abrió abrió rótulo
abeto abeto abeto abeto abeto consto
abren abren abren abren abren cebón
bella bella bella bella bella creerá
arder arder arder arder arder flexor
batan batan batan batan batan asiste
